-- Blog cache tables for faster page loads.
-- Run in Supabase SQL Editor or via Supabase CLI.

-- Trip-level cache (blog home cards + trip page hero/summary)
CREATE TABLE IF NOT EXISTS trips_cache (
  trip_name text PRIMARY KEY,
  cover_url text,
  first_date text,
  summary_text text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Per-day cache (trip page day list + day page content)
CREATE TABLE IF NOT EXISTS days_cache (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_name text NOT NULL,
  date text NOT NULL,
  cover_url text,
  hero_filename text,
  blog_post text,
  has_map boolean NOT NULL DEFAULT false,
  has_gpx boolean NOT NULL DEFAULT false,
  map_trail_url text,
  map_elevation_url text,
  trail_stats jsonb,
  stream_videos jsonb,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (trip_name, date)
);

CREATE INDEX IF NOT EXISTS idx_days_cache_trip ON days_cache (trip_name);

-- Photo URLs cache (display + thumb signed URLs)
CREATE TABLE IF NOT EXISTS photo_urls_cache (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_name text NOT NULL,
  date text NOT NULL,
  filename text NOT NULL,
  display_url text,
  thumb_url text,
  expires_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (trip_name, date, filename)
);

CREATE INDEX IF NOT EXISTS idx_photo_urls_cache_lookup ON photo_urls_cache (trip_name, date);
